name: Development Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: On Which Branch & Commit SHA
        run: echo Build \"${{ github.head_ref }}\" Commit \"${GITHUB_SHA}\"
      - name: Slack Start
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_TITLE: Status
          SLACK_MESSAGE: BUILD START
          SLACK_COLOR: warning
          SLACK_USERNAME: Github Action Notifier
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Build App
        run:  yarn && yarn build
      - name: Slack Notification - Success
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_TITLE: Status
          SLACK_MESSAGE: BUILD SUCCESS
          SLACK_USERNAME: Github Action Notifier
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_TITLE: Status
          SLACK_MESSAGE: BUILD FAILURE
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Action Notifier
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

